Moved processing scripts out of bin directory

diff --git a/collectLIDC b/collectLIDC
--- a/collectLIDC
+++ b/collectLIDC
@@ -1,168 +1,65 @@
 #!/bin/bash
+
+# Collect all the SQL files from every result directory
+
 # SGE Parameters
+## Name
+#$ -N collect_lidc
+
+## working directory
+#$ -cwd
+
+## Export variables
+#$ -V
+
+## Logs -- to /dev/null
+# -o /home/sgeadmin/logs/
+#$ -j yes
+#$ -e /dev/null
+#$ -o /dev/null
+
+
 # http://redsymbol.net/articles/unofficial-bash-strict-mode/
-# set -uo pipefail
+set -uo pipefail
 IFS=$'\n\t'
 shopt -s nullglob
-
-# Index the data generated by processLIDC
 
 # Some variables
 if [ `uname` = 'Linux' ]; then
 
     # Linux paths
-    export JAVA_HOME=/software/jvm/jdk1.8.0_20
     export PATH=$PATH:$JAVA_HOME/bin:/software/bin:/software/python
-    export LD_LIBRARY_PATH=/software/lib
-    export JAVA_OPTS="-Xmx2g"
-    # Python Virtual env
-    source /software/lidc-venv/bin/activate
-
-    # Get the XML file to run
-    XMLORIG=/software/$(sed "${JOBID}q;d" /software/lidc.txt)
-    algorithm_dir=/software/algorithms
 else
     # Mac path
     PATH=`pwd`/build/install/LIDCTooling/bin:$PATH
     PATH=`pwd`/../ChestImagingPlatform/build/CIP-build/bin/:`pwd`/python/:${PATH}
-    XMLORIG=ClusterSoftware/tcia-lidc-xml/157/158.xml
 fi
 
 # in 'main' we can reference functions later in the script
 main() {
+    
     # Database name
     DB=${1:-lidc.db}
     DB=$(fullPath $DB)
-    
+
+    printf "Collect LIDC Results\n"
     createDB
+    printf "Created database: %s\n" %DB
     wd=$(pwd)
+    printf "Indexing reads"
     # Index the reads
     for dir in segmented/*; do
-        cd $wd
-        indexRead $dir
-        cd $wd
-        indexFeatures $dir
-        cd $wd
-        indexMeasures $dir
-        cd $wd
-        captureErrors $dir
-    done
-    
-}
-
-
-function indexMeasures {
-    dir=$1
-    cd $dir
-    # Process all the measures
-    printf "Measures"
-    for fid in *_measures.json; do
-        printf "."
-        uid=$(jq -r '"\(.algorithm)-\(.nodule_uid)"' $fid)
-        getValues $fid . $uid measures
-        getValues $fid .measures $uid measures
-        sqlite3 $DB <<EOF
-update measures set path = '$dir' where uid = '$uid';
-EOF
-    done
-    printf "\n"
-}
-
-function indexRead {
-    dir=$1
-    cd $dir
-    getValues reads.json . $(jq -r .uid reads.json) series
-
-    for read_id in $(jq -r ".reads[].id" reads.json); do
-        read_uid=$(jq -r ".reads[] | select(.id == $read_id) | .uid" reads.json)
-        echo Read: $read_id uid $read_uid
-        getValues reads.json ".reads[] | select(.id == $read_id)" $read_uid reads
-        printf "Nodules"
-        for nodule_id in $(jq -r ".reads[] | select(.uid == \"$read_uid\") | .nodules[].id" reads.json); do
-            # printf "%s\n" "Processing Nodule: $nodule_uid"
+        if [[ -e $dir/results.sql ]]; then
             printf "."
-            jq ".reads[].nodules[] | select ( .id == \"$nodule_id\" )" reads.json > nodule.json
-            nodule_uid=$(jq -r .uid nodule.json)
-            getValues nodule.json . $nodule_uid nodules
-            getValues nodule.json .characteristics $nodule_uid nodules
-            sqlite3 $DB <<EOF
- update nodules set read_uid = '$read_uid' where uid = '$nodule_uid';
-EOF
-            #         nodule_uid=$(echo $nodule | jq -r ".uid")
-        done
-        printf "\n"
-    done
+            sqlite3 $DB < $dir/results.sql
+            if [[ $? -ne 0 ]]; then
+                printf "\n\n====\nFailed:\n$dir\n====\n\n" $dir
+            fi
 
-    
-    #     read=$(jq ".reads[] | select(.id == $read_id)" reads.json)
-    #     read_uid=$(echo $read | jq -r ".uid")
-    #     for nodule_id in $(echo $read | jq -r ".nodules[].id"); do
-    #         nodule=$(echo $read | jq ".nodules[] | select ( .id == \"$nodule_id\" )")
-    #         nodule_uid=$(echo $nodule | jq -r ".uid")
-    #         normalized_nodule_id=$(echo $nodule | jq -r ".normalized_nodule_id")
-    
-}
-
-function indexFeatures {
-    dir=$1
-    cd $dir
-    printf "Features"
-    for fid in *_features.json; do
-        printf "."
-        uid=$(jq -r '"\(.algorithm)-\(.nodule_uid)"' $fid)
-        getValues $fid . $uid features
-        getValues $fid ".first_order, .glcm, .glszm, .rlgl, .shape" $uid features
-        # for t in first_order glcm glszm rlgl shape; do
-        #     getValues $fid .${t} $uid features
-        # done
-    done
-    printf "\n"
-}
-
-
-function captureErrors {
-    dir=$1
-    cd $dir
-    length=$(jq -r '.errors | length' error.json)
-    echo Processing $length errors in $dir
-    ((length = length - 1))
-    # length=$(echo $((length--)))
-    for i in `seq 0 $length`; do
-        uid=$(uuidgen)
-        getValues error.json ".errors[$i]" $uid errors
-        p=$(jq -r ".errors[$i].log" error.json)
-        sqlite3 $DB <<EOF
-update errors set path = '$dir/$p' where uid = '$uid';
-EOF
-    done
-}
-
-function fullPath {
-    echo "$(cd "$(dirname "$1")"; pwd)/$(basename "$1")"
-}
-
-# Take a json file, JSON path, uid, and table to insert values into
-function getValues {
-    file=$1
-    path=$2
-    uid=$3
-    table=$4
-    # echo $file $path $uid $table
-    sqlite3 $DB <<EOF
-insert or ignore into $table ( uid ) values ( '$uid' );
-EOF
-    sql=""
-    # Get all the keys, but ignore keys named "uid"
-    for key in $(jq -r "$path | keys | .[]" $file); do
-        if [[ $tableinfo == *${key}* ]] && [[ $key != "uid" ]]; then
-            value=$(jq -r "$path | .[\"$key\"] // \"\" " $file | sed "s/'/''/g")
-            sql+="update or ignore $table set $key = '$value' where uid = '$uid'; "
         fi
     done
-    echo $sql | sqlite3 $DB
-#     <<EOF
-#  update or ignore $table set $key = '$value' where uid = '$uid';
-# EOF
+    printf "\n"
+    
 }
 
 function createDB {
@@ -471,6 +368,10 @@ done
 # Remove uid, including at the beginning of the string
 tableinfo=$(echo $tableinfo | sed 's/[[:space:]]uid//g' | sed 's/^uid//g')
 sqlite3 $DB "delete from errors;"
+}
+
+function fullPath {
+    echo "$(cd "$(dirname "$1")"; pwd)/$(basename "$1")"
 }
 
 main "$@"
